[core]
db_url = "postgresql://postgres:e4cqtvu2sHlmwEuy5wSG2ZkINrnxyLNSWpLikE8szXPly4X2NqWfkFKp48y3KKQn@162.55.81.185:3129/postgres"
polling_interval = 5000

# [[chains.evm]]
# name = "base"
# chain_id = 84532
# rpc_url = "https://base-sepolia-rpc.publicnode.com"
# contract_address = "0x048975f98b998796d1cF54DE3A3Fc2bE01d891Fd"
# start_block = 29219473


# [[chains.evm]]
# name = "monad"
# chain_id = 10143
# rpc_url = "https://rpc.ankr.com/monad_testnet"
# contract_address = "0xa62dF4c42fFd8a352436461f3A3542bF2EFb06bF"
# start_block = 29060696


[[chains.evm]]
name = "etherlink"
chain_id = 128123
rpc_url = "https://node.ghostnet.etherlink.com"
contract_address = "0x30d24e9d1Fbffad6883E8632c5ad4216c9A86dFC"
start_block = 20891277


[[chains.starknet]]
name = ""
chain_id = 0
rpc_url = ""
contract_address = ""
start_block = 0
